services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672: 5672"    # AMQP
      - "15672: 15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_db
    ports:
      - "5432: 5432"
  
  redis:
    image: redis:alpine
    ports:
      - "6379: 6379"
  
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"   # UI for Logs
    